load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "tpm_test_support",
    srcs = [
        "src/lib.rs",
        "src/metadata.rs",
        "src/test_random.rs",
        "src/tpm_config.rs",
    ],
    edition = "2021",
    deps = [
        "//third_party/tpm2_tss",
        "@rust_crates//:anyhow",
        "@rust_crates//:clap",
        "@rust_crates//:ecdsa",
        "@rust_crates//:enumflags2",
        "@rust_crates//:env_logger",
        "@rust_crates//:fastrand",
        "@rust_crates//:hex",
        "@rust_crates//:log",
        "@rust_crates//:num-traits",
        "@rust_crates//:p256",
        "@rust_crates//:rsa",
        "@rust_crates//:sha2",
        "@rust_crates//:tss-esapi",
    ],
)

rust_test(
    name = "tpm_test_support_test",
    crate = ":tpm_test_support",
    edition = "2021",
)
