load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_test")
load(":tpm_env.bzl", "tpm_proxy_environment", "tpm_simulator_environment")

package(default_visibility = ["//visibility:public"])

exports_files([
    "tpm_test.bzl",
    "tpm_env.bzl",
])

rust_binary(
    name = "tpm_test_runner",
    srcs = ["src/main.rs"],
    edition = "2021",
    deps = [
        "@rust_crates//:anyhow",
        "@rust_crates//:env_logger",
        "@rust_crates//:log",
    ],
)

rust_test(
    name = "device_lock_test",
    srcs = ["src/main.rs"],
    edition = "2021",
    deps = [
        "@rust_crates//:anyhow",
        "@rust_crates//:env_logger",
        "@rust_crates//:log",
    ],
)

tpm_simulator_environment(
    name = "simulator",
)

tpm_proxy_environment(
    name = "proxy",
    proxy_args = [
        "--device-type",
        "mock",
    ],
    proxy_bin = "//tpm_proxy:tpm_proxy",
)

tpm_proxy_environment(
    name = "mock_hw_0",
    lock_id = "mock_board_0",
    proxy_args = [
        "--device-type",
        "mock",
    ],
    proxy_bin = "//tpm_proxy:tpm_proxy",
)

tpm_proxy_environment(
    name = "mock_hw_1",
    lock_id = "mock_board_1",
    proxy_args = [
        "--device-type",
        "mock",
    ],
    proxy_bin = "//tpm_proxy:tpm_proxy",
)

label_flag(
    name = "tpm_environment",
    build_setting_default = ":simulator",
)
