load(":tpm_env.bzl", "TpmEnvInfo")

def _tpm_wrapped_test_impl(ctx):
    test_binary = ctx.executable.test_binary
    test_runner = ctx.executable.test_runner
    env_info = ctx.attr.environment[TpmEnvInfo]

    # Collect environment variables to export to the runner.
    env = dict(env_info.env)
    env["TEST_COMMAND"] = test_binary.short_path
    env["RUST_TEST_THREADS"] = "1"
    if ctx.executable.setup_tool:
        env["SETUP_TOOL"] = ctx.executable.setup_tool.short_path
    if ctx.executable.teardown_tool:
        env["TEARDOWN_TOOL"] = ctx.executable.teardown_tool.short_path

    # Generate the runner script.
    output_script = ctx.actions.declare_file(ctx.label.name + "_runner.sh")
    script_lines = [
        "#!/usr/bin/env bash",
        "set -euo pipefail",
        "# Generated by tpm_wrapped_test rule for " + ctx.label.name,
    ] + ['export {}="{}"'.format(k, v) for k, v in env.items()] + [
        'exec "./{}" "$@"'.format(test_runner.short_path),
    ]

    ctx.actions.write(
        output = output_script,
        content = "\n".join(script_lines) + "\n",
        is_executable = True,
    )

    # Collect runfiles: collect_default = True automatically gathers runfiles
    # from all rule attributes (test_binary, test_runner, setup_tool, teardown_tool, data).
    # We only need to provide any direct executables and merge TpmEnvInfo runfiles.
    runfiles_files = [test_runner, test_binary] + ctx.files.data
    if ctx.executable.setup_tool:
        runfiles_files.append(ctx.executable.setup_tool)
    if ctx.executable.teardown_tool:
        runfiles_files.append(ctx.executable.teardown_tool)

    runfiles = ctx.runfiles(
        files = runfiles_files,
        collect_default = True,
    ).merge(env_info.runfiles)

    return [
        DefaultInfo(
            executable = output_script,
            runfiles = runfiles,
        ),
    ]

_tpm_wrapped_test = rule(
    doc = "A custom test rule to run wrapped TPM tests.",
    implementation = _tpm_wrapped_test_impl,
    attrs = {
        "data": attr.label_list(
            allow_files = True,
            doc = "The list of files needed by this test at runtime.",
        ),
        "environment": attr.label(
            default = Label("//tpm_test_runner:tpm_environment"),
            doc = "The TPM environment to use.",
            providers = [TpmEnvInfo],
        ),
        "setup_tool": attr.label(
            cfg = "target",
            doc = "Optional Level 2 pre-test setup tool executable.",
            executable = True,
        ),
        "teardown_tool": attr.label(
            cfg = "target",
            doc = "Optional Level 2 post-test teardown tool executable.",
            executable = True,
        ),
        "test_binary": attr.label(
            cfg = "target",
            doc = "The actual test binary to run.",
            executable = True,
            mandatory = True,
        ),
        "test_runner": attr.label(
            cfg = "target",
            default = Label("//tpm_test_runner:tpm_test_runner"),
            doc = "The main Rust unified test runner binary.",
            executable = True,
        ),
    },
    test = True,
)

def tpm_wrapped_test(name, size = "small", **kwargs):
    _tpm_wrapped_test(
        name = name,
        size = size,
        **kwargs
    )

def tpm_test_suite(
        name,
        tests = [],
        size = "small",
        data = [],
        environment = None,
        setup_tool = None,
        teardown_tool = None,
        **kwargs):
    """Defines a test suite with parameterized tests by dynamically generating targets.

    Args:
        name: The name of the test suite.
        tests: Either a list of test targets (e.g. [":pcr_test", ":startup_test"]),
               or a dictionary mapping test targets to lists of override arguments
               (e.g. {":pcr_test": ["--verbose"], ":startup_test": []}).
        size: The size of the generated tests.
        data: The list of files needed by the tests at runtime.
        environment: Optional TPM test environment target override.
        setup_tool: Optional Level 2 pre-test setup tool target.
        teardown_tool: Optional Level 2 post-test teardown tool target.
        **kwargs: Additional arguments passed to the native test_suite (e.g., tags, visibility).
    """
    if type(tests) == "list":
        tests_dict = {t: [] for t in tests}
    elif type(tests) == "dict":
        tests_dict = tests
    else:
        fail("tpm_test_suite 'tests' attribute must be a list of labels or a dict mapping labels to argument lists")

    generated_tests = []

    for test_bin, args in tests_dict.items():
        bin_name = test_bin.split(":")[-1].split("/")[-1]
        wrapped_test_name = "{}_{}_wrapped".format(name, bin_name)

        tags = ["manual"] + [t for t in kwargs.get("tags", []) if t != "manual"]
        tpm_wrapped_test(
            name = wrapped_test_name,
            test_binary = test_bin,
            args = args,
            tags = tags,
            size = size,
            data = data,
            environment = environment,
            setup_tool = setup_tool,
            teardown_tool = teardown_tool,
        )

        generated_tests.append(":" + wrapped_test_name)

    native.test_suite(
        name = name,
        tests = generated_tests,
        **kwargs
    )
